build: Update PHPUnit from 9.x to 10.x and further to 12.x
== Annotations ==

PHPUnit 10 added a way to set annotations like dataProvider via native
attributes instead of docblocks.

PHPUnit 12 made these mandatory. E.g.:

```
PHPUnit 12.5.37
…
1) CacheTest::testValues
ArgumentCountError: Too few arguments to function CacheTestCase::testValues(), 0 passed in
/vendor/phpunit/phpunit/src/Framework/TestCase.php on line 1318 and exactly 2 expected
/test/unit/CacheTestCase.php:21
```

== Deprecations ==

```
PHPUnit 12.5.37
…
OK, but there were issues!
Tests: 38, Assertions: 90, PHPUnit Deprecations: 1.
```

These "PHPUnit" deprecations are hidden by default. I think they
should be made visible because one of these warnings is for
unrecognised XML elements in phpunit.xml, and that's not just a
deprecation but basically representing something that got removed
and no longer works. This should be visible upfront by setting
displayDetailsOnPhpunitDeprecations="true" or maybe even
failOnPhpunitDeprecation="true".

```
There was 1 PHPUnit test runner warning:
1) Test results may not be as expected because the XML configuration file did not pass validation:
  Line 13:
  - Element 'include': This element is not expected.
```

== Coverage sources ==

It's not obvious from the PHPUnit 10 blogpost, nor from current docs
at https://docs.phpunit.de/en/12.5/xml-configuration-file.html what
to do instead of `<coverage><include>`.

The PHPUnit 10 blog post links to
https://github.com/sebastianbergmann/phpunit/blob/10.0.0/ChangeLog-10.0.md#1000---2023-02-03
which links to
https://github.com/sebastianbergmann/phpunit/issues/5294
which explains that in order to power the new PHPUnit feature to
raise PHP-native deprecations (e.g. some new PHP 8.5 warning) without
also raising them for random vendor packages outside you control,
it now wants you to describe where your source code in generael
instead of only for the coverage report.

Basically, just change `<coverage><include>` to `<source><include>`.

Ref https://phpunit.de/announcements/phpunit-10.html
Ref https://phpunit.de/announcements/phpunit-12.html

Bug: T328919
Change-Id: I00cddd9f5fe0effbd8ea28ec275af5ca91b3a50f